project:
  type: website
  output-dir: docs

website:
  cookie-consent:
    type: express
    style: headline
    palette: light
  google-analytics: G-F6L2QHK99R
  title: ""
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/krisandraa
      - icon: linkedin
        href: https://www.linkedin.com/in/krisandraallen/
      - icon: github
        href: https://github.com/genomicepi
      - icon: envelope-at
        href: mailto:krisandra@genomicepi.com
    left:
      - href: index.qmd
        text: Home
      - href: publichealth.qmd
        text: Training
      - href: jobs.qmd
        text: Genomic Epi Jobs
      - href: programs.qmd
        text: Genomic Epi Graduate Programs
      - href: newsletter.qmd
        text: Newsletter
      - href: about_me.qmd
        text: About Me

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME


