project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/krisandraa
      - icon: linkedin
        href: https://www.linkedin.com/in/krisandraallen/
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - presentations.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

