---
title: "Genomic Epi Graduate Programs"
---

Are you interested in a graduate program in genomic epidemiology, or do you have a genomic epidemiology program you'd like to share? You've come to the right place!

This is intended to be a broad listing of both programs that are specifically focused on genomic epidemiology or closely-related disciplines, but also programs such as epidemiology PhD programs that have advisors available to allow students to complete genomic epidemiology focused research.


### Program map

Use your mouse to navigate the map as well as zoom in or out. You'll notice the map right now is US programs - I'd love your help expanding the list globally! Please reach out or submit programs using the form below on the page.
```{=html}
<iframe src="https://microreact.org/project/teDJWGS7NfzCeKYzq9Bwiw-grad-programs" frameborder="1" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>
```

### Program listing
```{=html}
<iframe class="airtable-embed" src="https://airtable.com/embed/appiZK1wyNNfgMDKq/shrHlSloHHcPIWcT7?backgroundColor=teal&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="350" style="background: transparent; border: 1px solid #ccc;"></iframe>
```

### Submit a program
Do you know of a graduate program that would be appropriate for someone interested in genomic epidemiology? Please submit it here to have it added to the list.
```{=html}
<iframe class="airtable-embed" src="https://airtable.com/embed/appopPYtAoGapvFmE/pagAX0eZKlDOgdRzZ/form" frameborder="0" onmousewheel="" width="100%" height="1200" style="background: transparent; border: 1px solid #ccc;"></iframe>
```
### Newsletter

```{=html}
<iframe src="https://genomicepi.substack.com/embed" width="100%" height="315" style="border:2px solid #78c2ad; background:#f3969a;" frameborder="0" scrolling="no"></iframe>
```
