---
title: "Training Resources"
---

### **Websites for genomic epidemiology in public health**

------------------------------------------------------------------------

-   **CDC's Advanced Molecular Detection (AMD)** [page](https://www.cdc.gov/amd/index.html) has a collection of resources and links out to additional resources such as the Pathogen Genomics Centers of Excellence. Another resource from AMD that I worked on with them is the [CDC Genomic Epidemiology Toolkit](https://www.cdc.gov/amd/training/covid-19-gen-epi-toolkit.html). It's a great resource and easy to work through since each module is self-contained and 10 minutes or less.

-   **The Council of State and Territorial Epidemiologists (CSTE)** has an Advanced Molecular Detection subcommittee that meets regularly and provides webinars. Interested CSTE members can join the meetings, and webinar recordings are available to all [here](https://www.cste.org/page/WebinarLibrary).

-   **The Association of Public Health Laboratories (APHL)** provides training and resources through their Annual meeting as well as other special topics meetings, trainings and webinars that you can search through [here](https://www.aphl.org/training/Pages/All-Laboratory-Training-Events-Search.aspx).

-   **State Public Health Bioinformatics Group (STAPH-B)** is a consortium of bioinformaticians in public health working together to overcome barriers and share best practices. Recorded meetings and other trainings are linked through their [website](https://staphb.org/).

-   **An applied genomic epidemiological handbook.** by Alli Black and Gytis Dudas, available [here](https://alliblk.github.io/genepi-book/).

-   **Wellcome Connecting Science** offers a variety of genomics and bioinformatics courses through [FutureLearn](https://www.futurelearn.com/partners/wellcome-genome-campus)

-   **Food Safety Centers of Excellence** offers a number of webinars and self-paced courses through their [website](https://foodsafetycoe.org/products/)

------------------------------------------------------------------------

### **Genomic epidemiology webinars and trainings**

``` html
<iframe class="airtable-embed" src="https://airtable.com/embed/appSloVkGaZAs0rOi/shr7x7TUgj219Hviy?backgroundColor=teal&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="800" style="background: transparent; border: 1px solid #ccc;"></iframe>
```

------------------------------------------------------------------------

### Self-Study Exercises

| Title                                                                                                                         | Description                                                                                                                                                                                                                                                                                                                                                                                           | Organizer                                                     |
|---------------|-------------------------------------------|---------------|
| [Digital Epidemiology Workshop](https://cgps-group.github.io/digitalepiworkshop/hands-on/exercise.html)                       | Hands on exercise using web-based tools (EpiCollect, Pathogenwatch, Data-flo, Microreact) to conduct a genomic epidemiology investigation.                                                                                                                                                                                                                                                            | Centre for Genomic Pathogen Surveillance                      |
| [Infectious Disease Genomic Epidemiology 2023](https://bioinformaticsdotca.github.io/IDE_2023)                                | This 4-day course from CBW provides an introduction to genomic epidemiology analysis followed by hands-on practical tutorials demonstrating the use of selected analysis tools. The tutorials are designed as self-contained units that include example data and detailed instructions for installation of all required bioinformatics tools or access to publicly available web applications.        | Bioinformatics.ca                                             |
| [Whole genome multi locus sequence typing activity](https://cals.cornell.edu/new-york-integrated-food-safety/wgmlst-activity) | This activity was developed by the New York Integrated Food Safety Center of Excellence to provide public health staff or students of public health with an understanding of how whole genome sequencing (WGS), and particularly whole genome multi locus sequence typing (wgMLST), works as a subtyping method. The activity can be taken individually or in group (3-5 people per group suggested). | New York Food Safety Center of Excellence/ Cornell University |

```{=html}
<iframe src="https://genomicepi.substack.com/embed" width="100%" height="315" style="border:2px solid #78c2ad; background:#f3969a;" frameborder="0" scrolling="no"></iframe>
```
